<?php

// WebEngine CMS Tables Prefix
define('WE_PREFIX', '');

// WebEngine CMS Tables
#User Tables
define('WEBENGINE_U_CORE', WE_PREFIX.'WEBENGINE_U_CORE');
define('WEBENGINE_USER_DETAILS', WE_PREFIX.'WEBENGINE_USER_DETAILS');
define('WEBENGINE_U_AUTH', WE_PREFIX. 'WEBENGINE_U_AUTH');
define('WEBENGINE_USER_SESSIONS', WE_PREFIX.'WEBENGINE_USER_SESSIONS');
define('WEBENGINE_BLOCKED_IPS', WE_PREFIX.'WEBENGINE_BLOCKED_IPS');
define('WEBENGINE_BLOCKED_LOG', WE_PREFIX.'WEBENGINE_BLOCKED_LOG');
define('WEBENGINE_REMEMBER_TOKENS', WE_PREFIX.'WEBENGINE_REMEMBER_TOKENS');
define('WEBENGINE_PASSWORD_RESETS', WE_PREFIX.'WEBENGINE_PASSWORD_RESETS');
define('WEBENGINE_NOTIFICATIONS', WE_PREFIX.'WEBENGINE_NOTIFICATIONS');

#Roles Tables
define('WEBENGINE_ROLES', WE_PREFIX.'WEBENGINE_ROLES');
define('WEBENGINE_USER_ROLES', WE_PREFIX.'WEBENGINE_USER_ROLES');
define('WEBENGINE_PERMISSIONS', WE_PREFIX.'WEBENGINE_PERMISSIONS');
define('WEBENGINE_USER_PERMISSIONS', WE_PREFIX.'WEBENGINE_USER_PERMISSIONS');
define('WEBENGINE_ROLES_PERMISSIONS', WE_PREFIX.'WEBENGINE_ROLES_PERMISSIONS');

#Projects
define('WEBENGINE_PROJECTS', WE_PREFIX.'WEBENGINE_PROJECTS');
define('WEBENGINE_PROJECT_RESEARCHERS', WE_PREFIX.'WEBENGINE_PROJECT_RESEARCHERS');
define('WEBENGINE_PROJECT_TEACHERS', WE_PREFIX.'WEBENGINE_PROJECT_TEACHERS');
define('WEBENGINE_PROJECT_REVIEWERS', WE_PREFIX.'WEBENGINE_PROJECT_REVIEWERS');
define('WEBENGINE_RESEARCH_LINES', WE_PREFIX.'WEBENGINE_RESEARCH_LINES');
define('WEBENGINE_RATINGS', WE_PREFIX.'WEBENGINE_RATINGS');
define('WEBENGINE_RATING_SUMMARY', WE_PREFIX.'WEBENGINE_RATING_SUMMARY');
define('WEBENGINE_EVALUATION_SESSIONS', WE_PREFIX.'WEBENGINE_EVALUATION_SESSIONS');
define('WEBENGINE_EVALUATION_PARTICIPANTS', WE_PREFIX.'WEBENGINE_EVALUATION_PARTICIPANTS');
define('WEBENGINE_REEVALUATIONS', WE_PREFIX.'WEBENGINE_REEVALUATIONS');

