<?php

if(!defined('access') or !access or access != 'install') die();

define('INSTALLER_VERSION', '1.2.6');
define('WEBENGINE_CONFIGURATION_FILE', 'webengine.json');
define('WEBENGINE_DEFAULT_CONFIGURATION_FILE', 'webengine.json.default');
define('WEBENGINE_WRITABLE_PATHS_FILE', 'writable.paths.json');

$install['sql_list'] = array(
	#User Tables
	'WEBENGINE_U_CORE' => WEBENGINE_U_CORE,
	'WEBENGINE_USER_DETAILS' => WEBENGINE_USER_DETAILS,
	'WEBENGINE_U_AUTH' => WEBENGINE_U_AUTH,
	'WEBENGINE_USER_SESSIONS' => WEBENGINE_USER_SESSIONS,
	'WEBENGINE_BLOCKED_IPS' => WEBENGINE_BLOCKED_IPS,
	'WEBENGINE_BLOCKED_LOG' => WEBENGINE_BLOCKED_LOG,
	'WEBENGINE_REMEMBER_TOKENS' => WEBENGINE_REMEMBER_TOKENS,
	'WEBENGINE_PASSWORD_RESETS' => WEBENGINE_PASSWORD_RESETS,
	'WEBENGINE_NOTIFICATIONS' => WEBENGINE_NOTIFICATIONS,

	#Roles Tables
	'WEBENGINE_ROLES' => WEBENGINE_ROLES,
	'WEBENGINE_PERMISSIONS' => WEBENGINE_PERMISSIONS,	
	'WEBENGINE_USER_ROLES' => WEBENGINE_USER_ROLES,
	'WEBENGINE_ROLES_PERMISSIONS' => WEBENGINE_ROLES_PERMISSIONS,
	'WEBENGINE_USER_PERMISSIONS' => WEBENGINE_USER_PERMISSIONS,
	
	#Projects Tables
	'WEBENGINE_PROJECTS' => WEBENGINE_PROJECTS,
	'WEBENGINE_PROJECT_RESEARCHERS' => WEBENGINE_PROJECT_RESEARCHERS,
	'WEBENGINE_PROJECT_TEACHERS' => WEBENGINE_PROJECT_TEACHERS,
	'WEBENGINE_PROJECT_REVIEWERS' => WEBENGINE_PROJECT_REVIEWERS,	
	'WEBENGINE_RESEARCH_LINES' => WEBENGINE_RESEARCH_LINES,
	'WEBENGINE_RATINGS' => WEBENGINE_RATINGS,
	'WEBENGINE_RATING_SUMMARY' => WEBENGINE_RATING_SUMMARY,
	'WEBENGINE_EVALUATION_PARTICIPANTS' => WEBENGINE_EVALUATION_PARTICIPANTS,
	'WEBENGINE_EVALUATION_SESSIONS' => WEBENGINE_EVALUATION_SESSIONS,
	'WEBENGINE_REEVALUATIONS' => WEBENGINE_REEVALUATIONS,
);

$install['step_list'] = array(
	array('install_intro.php', 'Introducción'),
	array('install_step_1.php', 'Requerimientos del sistema'),
	array('install_step_2.php', 'Conexión a la base de datos'),
	array('install_step_3.php', 'Creación de tablas'),
	array('install_step_4.php', 'Configuración usuario administrador'),
	array('install_step_5.php', 'Configuración del sitio'),
);